# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - pkg/pb  # Сгенерированный код

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Дефолтные
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Дополнительные
    - bodyclose
    - contextcheck
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tenv
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  lll:
    line-length: 120
    tab-width: 4

  misspell:
    locale: US

  goimports:
    local-prefixes: github.com/example/user-service

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - hugeParam

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  nestif:
    min-complexity: 4

  gomnd:
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '10'
      - '100'
    ignored-functions:
      - 'context.WithTimeout'
      - 'strconv.*'

issues:
  exclude-rules:
    # Игнорируем некоторые проверки для тестов
    - path: _test\.go
      linters:
        - dupl
        - gomnd
        - lll
        - funlen
        - goconst

    # Игнорируем для main.go
    - path: cmd/.*/main\.go
      linters:
        - gochecknoinits
        - gomnd

    # Игнорируем для сгенерированных файлов
    - path: \.pb\.go$
      linters:
        - all

  max-issues-per-linter: 50
  max-same-issues: 3