// Code generated by protoc-gen-go. DO NOT EDIT.
// Это заглушка для демонстрации структуры.
// В реальном проекте генерируется командой: make proto

package user_service

import (
	"context"

	"google.golang.org/grpc"
)

// UserStatus - статус пользователя.
type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USER_STATUS_ACTIVE      UserStatus = 1
	UserStatus_USER_STATUS_INACTIVE    UserStatus = 2
	UserStatus_USER_STATUS_BLOCKED     UserStatus = 3
)

// User - модель пользователя.
type User struct {
	Id        string
	Email     string
	Name      string
	Status    UserStatus
	CreatedAt int64
	UpdatedAt int64
}

// CreateUserRequest - запрос на создание пользователя.
type CreateUserRequest struct {
	Email    string
	Name     string
	Password string
}

// CreateUserResponse - ответ на создание пользователя.
type CreateUserResponse struct {
	User *User
}

// GetUserRequest - запрос на получение пользователя.
type GetUserRequest struct {
	Id string
}

// GetUserResponse - ответ на получение пользователя.
type GetUserResponse struct {
	User *User
}

// UpdateUserRequest - запрос на обновление пользователя.
type UpdateUserRequest struct {
	Id     string
	Email  *string
	Name   *string
	Status *UserStatus
}

// UpdateUserResponse - ответ на обновление пользователя.
type UpdateUserResponse struct {
	User *User
}

// DeleteUserRequest - запрос на удаление пользователя.
type DeleteUserRequest struct {
	Id string
}

// DeleteUserResponse - ответ на удаление пользователя.
type DeleteUserResponse struct{}

// UserFilter - фильтры для поиска пользователей.
type UserFilter struct {
	Ids      []string
	Emails   []string
	Statuses []UserStatus
}

// ListUsersRequest - запрос на список пользователей.
type ListUsersRequest struct {
	Filter *UserFilter
	Limit  int32
	Offset int32
}

// ListUsersResponse - ответ на список пользователей.
type ListUsersResponse struct {
	Users []*User
	Total int32
}

// UserServiceClient - клиент сервиса.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
}

// UserServiceServer - серверный интерфейс.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer - базовая реализация для forward compatibility.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// RegisterUserServiceServer регистрирует сервер.
func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

// UserService_ServiceDesc - описание сервиса.
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user_service.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "CreateUser"},
		{MethodName: "GetUser"},
		{MethodName: "UpdateUser"},
		{MethodName: "DeleteUser"},
		{MethodName: "ListUsers"},
	},
	Streams: []grpc.StreamDesc{},
}
